const EnumsErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABE_ERROR: 3,
    PRODUCT_MISSING_ERROR: 4,
    PRODUCT_EXIST_ERROR: 5,
    CART_MISSING_ERROR: 6,
    USER_EXIST_ERROR: 7,
    USER_MISSING_ERROR: 8,
    PSW_EXISTS_ERROR: 9,
    UPLOAD_MISSING_ERROR: 10,
    INVALID_TOKEN_ERROR: 11,
    UNAUTHORIZED_ACCESS_ERROR: 12
};

export default EnumsErrors